# Generated by Django 5.0.2 on 2024-04-01 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cramschool_common', '0002_category'),
        ('cramschool_management', '0002_alter_info_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='category',
        ),
        migrations.CreateModel(
            name='CategoryByInfo',
            fields=[
                ('category_by_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cramschool_common.category')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cramschool_management.info')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
